[project]
name = "geolocation"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jett Chen <jettchen12345@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.12.1.*"
pandas = "2.1.4.*"
pytorch = "2.1.0.*"
numpy = "1.26.2.*"
